frr version 10.7.0
frr defaults traditional
hostname bgp-vm
log syslog informational
service integrated-vtysh-config

ip prefix-list MALICIOUS seq 10 permit 198.51.100.0/24
ip prefix-list MALICIOUS seq 20 permit 203.0.113.0/24
ip prefix-list MALICIOUS seq 30 permit 192.0.2.0/24

route-map SET_SINKHOLE_NH permit 10
 match ip address prefix-list MALICIOUS
 set ip next-hop <SINKHOLE_PRIVATE_IP>
exit

route-map SET_SINKHOLE_NH permit 20
exit

ip route 192.0.2.0/24 <SINKHOLE_PRIVATE_IP>
ip route 198.51.100.0/24 <SINKHOLE_PRIVATE_IP>
ip route 203.0.113.0/24 <SINKHOLE_PRIVATE_IP>

router bgp 65001
 bgp router-id <BGP_PRIVATE_IP>
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor <ISP_PRIVATE_IP> remote-as 65002
 neighbor <ISP_PRIVATE_IP> description ISP-VM
 neighbor <ISP_PRIVATE_IP> ebgp-multihop 2
 neighbor <ISP_PRIVATE_IP> disable-connected-check
 neighbor <ISP_PRIVATE_IP> update-source ens5
 neighbor <ISP_PRIVATE_IP> timers connect 10
 address-family ipv4 unicast
  network <BGP_SUBNET_CIDR>
  network 192.0.2.0/24
  network 198.51.100.0/24
  network 203.0.113.0/24
  neighbor <ISP_PRIVATE_IP> soft-reconfiguration inbound
  neighbor <ISP_PRIVATE_IP> route-map SET_SINKHOLE_NH out
 exit-address-family

line vty
