frr version 10.7.0
frr defaults traditional
hostname bgp-vm
log syslog informational
service integrated-vtysh-config

ip prefix-list MALICIOUS seq 10 permit 198.51.100.0/24
ip prefix-list MALICIOUS seq 20 permit 203.0.113.0/24
ip prefix-list MALICIOUS seq 30 permit 192.0.2.0/24

route-map SET_SINKHOLE_NH permit 10
 match ip address prefix-list MALICIOUS
 set ip next-hop 172.31.19.2
exit

route-map SET_SINKHOLE_NH permit 20
exit

ip route 192.0.2.0/24 172.31.19.2
ip route 198.51.100.0/24 172.31.19.2
ip route 203.0.113.0/24 172.31.19.2

router bgp 65001
 bgp router-id 172.31.3.212
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.31.19.157 remote-as 65002
 neighbor 172.31.19.157 description ISP-VM
 neighbor 172.31.19.157 ebgp-multihop 2
 neighbor 172.31.19.157 disable-connected-check
 neighbor 172.31.19.157 update-source ens5
 neighbor 172.31.19.157 timers connect 10
 address-family ipv4 unicast
  network 172.31.0.0/20
  network 192.0.2.0/24
  network 198.51.100.0/24
  network 203.0.113.0/24
  neighbor 172.31.19.157 soft-reconfiguration inbound
  neighbor 172.31.19.157 route-map SET_SINKHOLE_NH out
 exit-address-family

line vty
