frr version 10.7.0
frr defaults traditional
hostname isp-vm
log syslog informational
service integrated-vtysh-config

ip route 0.0.0.0/0 172.31.16.1

router bgp 65002
 bgp router-id 172.31.19.157
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.31.3.212 remote-as 65001
 neighbor 172.31.3.212 description BGP-VM
 neighbor 172.31.3.212 ebgp-multihop 2
 neighbor 172.31.3.212 disable-connected-check
 address-family ipv4 unicast
  network 172.31.16.0/20
  neighbor 172.31.3.212 soft-reconfiguration inbound
 exit-address-family

line vty
