frr version 10.7.0
frr defaults traditional
hostname isp-vm
log syslog informational
service integrated-vtysh-config

ip route 0.0.0.0/0 <ISP_SUBNET_GW>

router bgp 65002
 bgp router-id <ISP_PRIVATE_IP>
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor <BGP_PRIVATE_IP> remote-as 65001
 neighbor <BGP_PRIVATE_IP> description BGP-VM
 neighbor <BGP_PRIVATE_IP> ebgp-multihop 2
 neighbor <BGP_PRIVATE_IP> disable-connected-check
 address-family ipv4 unicast
  network <ISP_SUBNET_CIDR>
  neighbor <BGP_PRIVATE_IP> soft-reconfiguration inbound
 exit-address-family

line vty
